// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileEntry represents a single item found during a directory scan.
 * The backend determines isDir from the OS; the frontend should not guess it.
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}
