// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as markdown$0 from "../../pkg/markdown/models.js";

/**
 * Bookmark represents a single bookmarked document.
 */
export class Bookmark {
    /**
     * Creates a new Bookmark instance.
     * @param {Partial<Bookmark>} [$$source = {}] - The source object to create the Bookmark.
     */
    constructor($$source = {}) {
        if (!("relPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relPath"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Bookmark}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bookmark(/** @type {Partial<Bookmark>} */($$parsedSource));
    }
}

/**
 * DocumentResult is the response returned by GetDocument.
 */
export class DocumentResult {
    /**
     * Creates a new DocumentResult instance.
     * @param {Partial<DocumentResult>} [$$source = {}] - The source object to create the DocumentResult.
     */
    constructor($$source = {}) {
        if (!("html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["html"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("headings" in $$source)) {
            /**
             * @member
             * @type {markdown$0.Heading[]}
             */
            this["headings"] = [];
        }
        if (!("relPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headings" in $$parsedSource) {
            $$parsedSource["headings"] = $$createField2_0($$parsedSource["headings"]);
        }
        return new DocumentResult(/** @type {Partial<DocumentResult>} */($$parsedSource));
    }
}

/**
 * RecentFolder represents a single entry in the recent folders list.
 */
export class RecentFolder {
    /**
     * Creates a new RecentFolder instance.
     * @param {Partial<RecentFolder>} [$$source = {}] - The source object to create the RecentFolder.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("lastOpened" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastOpened"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentFolder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentFolder}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentFolder(/** @type {Partial<RecentFolder>} */($$parsedSource));
    }
}

/**
 * TabInfo represents a single open tab for persistence.
 */
export class TabInfo {
    /**
     * Creates a new TabInfo instance.
     * @param {Partial<TabInfo>} [$$source = {}] - The source object to create the TabInfo.
     */
    constructor($$source = {}) {
        if (!("relPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relPath"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TabInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabInfo(/** @type {Partial<TabInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = markdown$0.Heading.createFrom;
const $$createType1 = $Create.Array($$createType0);
