// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Heading represents a single heading extracted from a Markdown document.
 */
export class Heading {
    /**
     * Creates a new Heading instance.
     * @param {Partial<Heading>} [$$source = {}] - The source object to create the Heading.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["level"] = 0;
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Heading instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Heading}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Heading(/** @type {Partial<Heading>} */($$parsedSource));
    }
}
