// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderService handles opening local folders via the native OS directory picker.
 * It also manages the file system watcher for the currently open folder.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanner$0 from "../../pkg/scanner/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../../pkg/search/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBookmark adds a document to the bookmarks table for the given project.
 * @param {string} rootPath
 * @param {string} relPath
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function AddBookmark(rootPath, relPath, title) {
    return $Call.ByID(4240024532, rootPath, relPath, title);
}

/**
 * AddRecentFolder inserts or updates a folder in the recent list.
 * Called every time the user opens a folder successfully.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function AddRecentFolder(path) {
    return $Call.ByID(1234210707, path);
}

/**
 * CloseProject stops the file watcher and cleans up.
 * @returns {$CancellablePromise<void>}
 */
export function CloseProject() {
    return $Call.ByID(2080407592);
}

/**
 * GetBookmarks returns all bookmarks for the given project, validating each
 * against the filesystem. Stale entries (deleted or renamed files) are
 * automatically removed from the database.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.Bookmark[]>}
 */
export function GetBookmarks(rootPath) {
    return $Call.ByID(2360573936, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetDocument reads a Markdown file from disk, renders it to HTML using
 * Goldmark, and returns the result along with extracted headings and title.
 * The frontend calls this when the user clicks a file in the FileTree.
 * @param {string} rootPath
 * @param {string} relPath
 * @returns {$CancellablePromise<$models.DocumentResult>}
 */
export function GetDocument(rootPath, relPath) {
    return $Call.ByID(3023618490, rootPath, relPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetFileTree scans the given rootPath for Markdown files and returns the
 * resulting FileEntry slice. Each entry contains the relative path and an
 * isDir flag determined by the OS, so the frontend never has to guess.
 * 
 * Excluded directories are resolved via ResolveExcludes, which checks for a
 * local .dokuignore file or falls back to global settings.
 * @param {string} rootPath
 * @returns {$CancellablePromise<scanner$0.FileEntry[]>}
 */
export function GetFileTree(rootPath) {
    return $Call.ByID(2798134873, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetLastFolder returns the most recently opened folder, but only if it still
 * exists on disk. If the path was deleted or the recent list is empty, returns
 * an empty string. This is the folder that will be auto-opened on startup.
 * @returns {$CancellablePromise<string>}
 */
export function GetLastFolder() {
    return $Call.ByID(62601019);
}

/**
 * GetOpenTabs retrieves the persisted open tabs for a project, ordered by position.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.TabInfo[]>}
 */
export function GetOpenTabs(rootPath) {
    return $Call.ByID(1332864571, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetRecentFolders returns up to 50 recent folders, validating each against
 * the filesystem. Entries whose path no longer exists are removed from the
 * database automatically so the list never shows stale entries.
 * @returns {$CancellablePromise<$models.RecentFolder[]>}
 */
export function GetRecentFolders() {
    return $Call.ByID(1153097633).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * IndexProject opens the index database for the given project root, scans all
 * Markdown files, and begins indexing them asynchronously. Progress events are
 * emitted to the frontend via Wails3 runtime events.
 * 
 * The frontend should call GetFileTree first to display the tree immediately,
 * then call IndexProject to start background indexing.
 * @param {string} rootPath
 * @returns {$CancellablePromise<void>}
 */
export function IndexProject(rootPath) {
    return $Call.ByID(3090418480, rootPath);
}

/**
 * OpenFolder opens the native OS directory picker and returns the selected path.
 * The frontend calls this when the user clicks "Browse" or presses Ctrl+O/⌘O.
 * Returns the absolute path to the selected folder, or an empty string if cancelled.
 * @returns {$CancellablePromise<string>}
 */
export function OpenFolder() {
    return $Call.ByID(2622795729);
}

/**
 * RemoveBookmark removes a document from the bookmarks table.
 * @param {string} rootPath
 * @param {string} relPath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveBookmark(rootPath, relPath) {
    return $Call.ByID(4094943129, rootPath, relPath);
}

/**
 * RemoveRecentFolder deletes a single entry from the recent folders list.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveRecentFolder(path) {
    return $Call.ByID(4111641902, path);
}

/**
 * SaveOpenTabs persists the list of open tabs for a project.
 * It replaces all existing entries with the provided list.
 * @param {string} rootPath
 * @param {$models.TabInfo[]} tabs
 * @returns {$CancellablePromise<void>}
 */
export function SaveOpenTabs(rootPath, tabs) {
    return $Call.ByID(3910621276, rootPath, tabs);
}

/**
 * SearchAll runs a full-text search across all indexed documents in the project.
 * @param {string} rootPath
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<search$0.Result[]>}
 */
export function SearchAll(rootPath, query, limit) {
    return $Call.ByID(771128088, rootPath, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SearchByPath searches for documents whose relative path contains the query.
 * @param {string} rootPath
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<search$0.Result[]>}
 */
export function SearchByPath(rootPath, query, limit) {
    return $Call.ByID(2473406247, rootPath, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SearchByTitle restricts the search to document titles only.
 * @param {string} rootPath
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<search$0.Result[]>}
 */
export function SearchByTitle(rootPath, query, limit) {
    return $Call.ByID(3886979254, rootPath, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Bookmark.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DocumentResult.createFrom;
const $$createType3 = scanner$0.FileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.TabInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.RecentFolder.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = search$0.Result.createFrom;
const $$createType10 = $Create.Array($$createType9);
