// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService exposes native window operations (minimise, maximise, close) to the frontend.
 * These replace the system titlebar since the app uses a custom titlebar.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close closes the application window and terminates the app.
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(257021087);
}

/**
 * Maximise toggles the window between maximised and normal state.
 * @returns {$CancellablePromise<void>}
 */
export function Maximise() {
    return $Call.ByID(3671187662);
}

/**
 * Minimise minimises the application window.
 * @returns {$CancellablePromise<void>}
 */
export function Minimise() {
    return $Call.ByID(809307180);
}
